version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ${awsregion})
  build:
    commands:
      - echo Build started on 'date'
      - mvn clean compile
      - mvn package -DskipTests
      - echo Building the Docker image...       
      #- docker build -t ${dockerimagename}:$CODEBUILD_RESOLVED_SOURCE_VERSION .
      - docker build -t ${dockerimagename}:${imgversion} .
      - docker tag ${dockerimagename}:${imgversion} ${awsaccountid}.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${dockerimagename}:${imgversion}
  post_build:
    commands:
      - echo Build completed on 'date'
      - echo Pushing the Docker image...
      - docker push ${awsaccountid}.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${dockerimagename}:${imgversion}
